const pressureProfile = {
  profileName: "Blooming Espresso",
  profilerId: "time-and-pressue",
  profilerFile: "time-and-pressure.profiler.js",
  stages: [
    {
      name: "Pre Infusion Ramp Up",
      time: {
        name: "Time",
        id: "pre-infusion-ramp-time",
        type: "time",
        min: 0,
        max: 10,
        defaultValue: 5,
        unit: "seconds",
        control: "slider",
      },
      pressure: {
        name: "Pressure",
        id: "pre-infusion-ramp-pressure",
        type: "pressure",
        min: 0,
        max: 5,
        defaultValue: 3,
        unit: "bars",
        control: "slider",
      },
    },
    {
      name: "Pre Infusion",
      time: {
        name: "Time",
        id: "pre-infusion-time",
        type: "time",
        min: 15,
        max: 30,
        defaultValue: 20,
        unit: "seconds",
        control: "slider",
      },
      pressure: {
        name: "Pressure",
        id: "pre-infusion-pressure",
        type: "pressure",
        min: 0,
        max: 5,
        defaultValue: 3.5,
        unit: "bars",
        control: "slider",
      },
    },
    {
      name: "Bloom",
      time: {
        name: "Time",
        id: "bloom-time",
        defaultValue: 30,
        min: 20,
        max: 40,
        unit: "seconds",
        control: "slider",
      },
      pressure: {
        name: "Pressure",
        id: "bloom-pressure",
        type: "pressure",
        min: 0,
        max: 5,
        defaultValue: 0,
        unit: "bars",
        control: "slider",
      },
    },
    {
      name: "Ramp",
      time: {
        name: "Ramp-up Time",
        id: "pressure-ramp-up-time",
        type: "time",
        min: 0,
        max: 10,
        defaultValue: 5,
        unit: "seconds",
        control: "slider",
      },
      pressure: {
        name: "Pressure",
        id: "ramp-up-pressure",
        type: "pressure",
        min: 4,
        max: 10,
        defaultValue: 9,
        unit: "bars",
        control: "slider",
      },
    },
    {
      name: "Infusion",
      time: {
        name: "Time",
        id: "infusion-time",
        type: "time",
        min: 0,
        max: 80,
        defaultValue: 50,
        unit: "seconds",
        control: "slider",
      },
      pressure: {
        name: "End Pressure",
        id: "infusion-pressure",
        type: "pressure",
        min: 4,
        max: 10,
        defaultValue: 7,
        unit: "bars",
        control: "slider",
      },
    },
  ],
};

export default pressureProfile;
