const pressureProfile = {
  profileName: "Simple Five Stage",
  profilerId: "time-and-pressure",
  profilerFile: "time-and-pressure.profiler.js",
  setup: {
    name: "Setup",
    temp: {
      name: "Initial Temperature",
      id: "setup-temperature",
      type: "temperature",
      min: 85,
      max: 99,
      defaultValue: 93.0,
      units: "c",
      control: "slider",
    },
  },
  stages: [
    {
      name: "Pre Infusion Ramp Up",
      id: "pre-infusion-ramp-up",
      time: {
        name: "Time",
        id: "pre-infusion-time",
        type: "time",
        min: 0,
        max: 20,
        defaultValue: 3,
        unit: "seconds",
        control: "slider",
      },
      pressure: {
        name: "Pressure",
        id: "pre-infusion-pressure",
        type: "pressure",
        min: 0,
        max: 10,
        defaultValue: 3,
        unit: "bars",
        control: "slider",
      },
    },
    {
      name: "Pre Infusion",
      id: "pre-infusion",
      time: {
        name: "Time",
        defaultValue: 5,
        min: 0,
        max: 30,
        unit: "seconds",
        control: "slider",
      },
      pressure: {
        name: "Pressure",
        id: "bloom-pressure",
        type: "pressure",
        min: 0,
        max: 10,
        defaultValue: 3,
        unit: "bars",
        control: "slider",
      },
    },
    {
      name: "Ramp",
      id: "ramp",
      time: {
        name: "Ramp-up Time",
        id: "pressure-ramp-up-time",
        type: "time",
        min: 0,
        max: 10,
        defaultValue: 5,
        unit: "seconds",
        control: "slider",
      },
      pressure: {
        name: "Pressure",
        id: "ramp-up-pressure",
        type: "pressure",
        min: 0,
        max: 10,
        defaultValue: 9,
        unit: "bars",
        control: "slider",
      },
    },
    {
      name: "Infusion",
      id: "infusion",
      time: {
        name: "Time",
        id: "infusion-time",
        type: "time",
        min: 0,
        max: 60,
        defaultValue: 20,
        unit: "seconds",
        control: "slider",
      },
      pressure: {
        name: "Pressure",
        id: "infusion-pressure",
        type: "pressure",
        min: 0,
        max: 10,
        defaultValue: 8,
        unit: "bars",
        control: "slider",
      },
    },
  ],
};

export default pressureProfile;
